name: pull_request

on:
  push:
    branches:
      - 'release/*'
      - 'develop'
      - 'master'
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: stanfordbdhg/action-swiftlint@v4
        with:
          args: --strict

  Build:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4

        - name: Xcode Setup
          uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '14.1'

        - name: Build
          run: |
            cd GitHubActions
            xcodebuild build -project GitHubActions.xcodeproj -scheme GitHubActions clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

        - name: Run tests
          run: |
            cd GitHubActions
            xcodebuild test -project GitHubActions.xcodeproj -scheme GitHubActions clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No