name: Swift

on:
  push:
    branches:
      - 'release/*'
      - 'develop'
      - 'master'
  pull_request:
    branches:
      - 'release/*'
      - 'develop'
      - 'master'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
